---
# tasks file for apt_autostart

- name: autostart | Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: autostart | Manage automatic service management
  when:
    - ansible_pkg_mgr == "apt"
  block:
    - name: autostart | Disable automatic service management on installation
      ansible.builtin.copy:
        dest: /usr/sbin/policy-rc.d
        content: "exit 101"
        mode: "755"
      when:
        - apt_autostart_state == "disabled"

    - name: autostart | Enable automatic service management on installation
      ansible.builtin.file:
        path: /usr/sbin/policy-rc.d
        state: absent
      when:
        - apt_autostart_state == "enabled"
