---
- name: setup-RedHat | Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
  when: ansible_default_ipv4.gateway is defined

- name: setup-RedHat | Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 2

- name: setup-RedHat | Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 4
